function [fitresult, gof] = createFit(X, N3, counts, threshold, smoothingParam)
    %CREATEFIT(X,N3)
    %  Create a fit.
    %
    %  Data for 'untitled fit 1' fit:
    %      X Input : X
    %      Y Output: N3
    %  Output:
    %      fitresult : a fit object representing the fit.
    %      gof : structure with goodness-of fit info.
    %
    %  See also FIT, CFIT, SFIT.
    
    %  Auto-generated by MATLAB on 01-Jul-2015 12:34:45
    
    
    % use some sort of default threshold if none is passed in as an
    % argument
    if nargin<4
        threshold = 3e-3;
    end
    
    if nargin<5
        smoothingParam = 0.97;
    end
    %% Fit: 'untitled fit 1'.
    [xData, yData, counts] = prepareCurveData( X, N3, counts );
    
    % Set up fittype and options.
    ft = fittype( 'smoothingspline' );
    opts = fitoptions( 'Method', 'SmoothingSpline' );
    opts.SmoothingParam = smoothingParam;
    opts.Exclude = counts < threshold;
    
    % Fit model to data.
    [fitresult, gof] = fit( xData, yData, ft, opts );
    
